// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HansKindberg.IdentityServer.DataProtection.Data.Migrations.SqlServer
{
	[DbContext(typeof(SqlServerDataProtection))]
	partial class SqlServerDataProtectionModelSnapshot : ModelSnapshot
	{
		#region Methods

		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.10")
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int")
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("FriendlyName")
					.HasColumnType("nvarchar(max)");

				b.Property<string>("Xml")
					.HasColumnType("nvarchar(max)");

				b.HasKey("Id");

				b.ToTable("DataProtectionKeys");
			});
#pragma warning restore 612, 618
		}

		#endregion
	}
}