// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace HansKindberg.IdentityServer.DataProtection.Data.Migrations.Sqlite
{
	[DbContext(typeof(SqliteDataProtection))]
	partial class SqliteDataProtectionModelSnapshot : ModelSnapshot
	{
		#region Methods

		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "5.0.3");

			modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("INTEGER");

				b.Property<string>("FriendlyName")
					.HasColumnType("TEXT COLLATE NOCASE");

				b.Property<string>("Xml")
					.HasColumnType("TEXT COLLATE NOCASE");

				b.HasKey("Id");

				b.ToTable("DataProtectionKeys");
			});
#pragma warning restore 612, 618
		}

		#endregion
	}
}