name: "Identity-Server Docker deploy"

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:  

jobs:
  build-and-deploy:
    name: "Build & deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Set up Docker QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Replace Application.csproj"
        run: cp "Source/Implementations/Identity-Server/Application/Application.csproj.deploy" "Source/Implementations/Identity-Server/Application/Application.csproj"
      - name: "Application.csproj content"
        run: cat "Source/Implementations/Identity-Server/Application/Application.csproj"
      - name: "Install npm"
        run: npm install
        working-directory: "Source/Implementations/Identity-Server/Application"
      - name: "Bundle client-assets (css, images & scripts)"
        run: gulp
        working-directory: "Source/Implementations/Identity-Server/Application"
      - name: "Sign in to DockerHub"
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: "Get current date"
        id: today
        run: echo "::set-output name=value::$(date +'%Y%m%d')"
      - name: "Build and push Docker-image"
        uses: docker/build-push-action@v2
        with:
          context: "Source/Implementations/Identity-Server"
          file: "Source/Implementations/Identity-Server/Application/Dockerfile"
          push: true
          tags: hanskindberg/identity-server:latest,hanskindberg/identity-server:${{ steps.today.outputs.value }}.${{ github.run_number }}